#!/bin/sh
#
# mocula
#

[ -f /media/mmc/mconfig ] || exit 0

case "$1" in
  start)
    # iCamera_app が /tmp/resolv.conf を上書きするため、udhcpc に RENEW を送って DNS を復元する
    kill -USR1 $(pgrep udhcpc) > /dev/null 2>&1
    sleep 1
    /scripts/mocula.sh on &
    ;;
  stop)
    /scripts/mocula.sh off
    ;;
  restart|reload)
    /scripts/mocula.sh restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
